<a href="https://colab.research.google.com/github/baselhusam/Data-Preparation-Course-IEEE-CIS/blob/main/Lec3_Cleaning_%26_Preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df = pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv")


## Data Cleaning

### Handling Missing Values

#### Using Pandas

In [ ]:
# check for missing values
print("Missing values before imputation:")
print(df.isnull().sum())

Missing values before imputation:
PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64


In [ ]:
# fill missing values in the 'Age' column with the mean
df['Age'].fillna(df['Age'].mean())

0      22.000000
1      38.000000
2      26.000000
3      35.000000
4      35.000000
         ...    
886    27.000000
887    19.000000
888    29.699118
889    26.000000
890    32.000000
Name: Age, Length: 891, dtype: float64

In [ ]:
# fill missing values in the 'Age' column with the median
df['Age'].fillna(df['Age'].median())

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ... 
886    27.0
887    19.0
888    28.0
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

In [ ]:
# fill missing values in the 'Embarked' column with the mode
df['Embarked'].fillna(df['Embarked'].mode()[0])

0      S
1      C
2      S
3      S
4      S
      ..
886    S
887    S
888    S
889    C
890    Q
Name: Embarked, Length: 891, dtype: object

In [ ]:
# fill missing values in the 'Cabin' column with a constant value ('unknown')
df['Cabin'].fillna('unknown')

0      unknown
1          C85
2      unknown
3         C123
4      unknown
        ...   
886    unknown
887        B42
888    unknown
889       C148
890    unknown
Name: Cabin, Length: 891, dtype: object

In [ ]:
# check for missing values after imputation
print("\nMissing values after imputation:")
print(df.isnull().sum())


Missing values after imputation:
PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64


#### Using `SimpleImputer` from `sklearn`

In [ ]:
from sklearn.impute import SimpleImputer

In [ ]:
mean_imputer = SimpleImputer(strategy='mean')
mean_imputer.fit_transform(df[['Age']])

# handle missing values using median
median_imputer = SimpleImputer(strategy='median')
median_imputer.fit_transform(df[['Age']])

# handle missing values using mode
mode_imputer = SimpleImputer(strategy='most_frequent')
mode_imputer.fit_transform(df[['Embarked']])

# handle missing values using constant value
constant_imputer = SimpleImputer(strategy='constant', fill_value='unknown')

In [ ]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [ ]:
df['Age'].fillna(df['Age'].median(), inplace=True)
df['Embarked'].fillna(df['Embarked'].mode()[0], inplace=True)
# df.drop(columns='Cabin', inplace=True)

### Outliers

In [ ]:
q1, q3 = df['Age'].quantile([0.25,0.75])
iqr = q3 - q1

upp_bound = q3 + 1.5 * iqr
low_bound = q1 - 1.5 * iqr

In [ ]:
df[~df['Age'].between(low_bound, upp_bound)].head(15)

PassengerId  Survived  Pclass                               Name     Sex  \
7              8         0       3     Palsson, Master. Gosta Leonard    male   
11            12         1       1           Bonnell, Miss. Elizabeth  female   
15            16         1       2   Hewlett, Mrs. (Mary D Kingcome)   female   
16            17         0       3               Rice, Master. Eugene    male   
33            34         0       2              Wheadon, Mr. Edward H    male   
54            55         0       1     Ostby, Mr. Engelhart Cornelius    male   
78            79         1       2      Caldwell, Master. Alden Gates    male   
94            95         0       3                  Coxon, Mr. Daniel    male   
96            97         0       1          Goldschmidt, Mr. George B    male   
116          117         0       3               Connors, Mr. Patrick    male   
119          120         0       3  Andersson, Miss. Ellis Anna Maria  female   
152          153         0       3                   Meo, Mr. Alfonzo    male   
164          165         0       3       Panula, Master. Eino Viljami    male   
170          171         0       1          Van der hoef, Mr. Wyckoff    male   
172          173         1       3       Johnson, Miss. Eleanor Ileen  female   

       Age  SibSp  Parch      Ticket     Fare Cabin Embarked  
7     2.00      3      1      349909  21.0750   NaN        S  
11   58.00      0      0      113783  26.5500  C103        S  
15   55.00      0      0      248706  16.0000   NaN        S  
16    2.00      4      1      382652  29.1250   NaN        Q  
33   66.00      0      0  C.A. 24579  10.5000   NaN        S  
54   65.00      0      1      113509  61.9792   B30        C  
78    0.83      0      2      248738  29.0000   NaN        S  
94   59.00      0      0      364500   7.2500   NaN        S  
96   71.00      0      0    PC 17754  34.6542    A5        C  
116  70.50      0      0      370369   7.7500   NaN        Q  
119   2.00      4      2      347082  31.2750   NaN        S  
152  55.50      0      0  A.5. 11206   8.0500   NaN        S  
164   1.00      4      1     3101295  39.6875   NaN        S  
170  61.00      0      0      111240  33.5000   B19        S  
172   1.00      1      1      347742  11.1333   NaN        S

### Data Duplicate

In [ ]:
# count the number of duplicates in the dataset
num_duplicates = df.duplicated().sum()

In [ ]:
# drop duplicates from the dataset and keep the first occurrence
df.drop_duplicates(inplace=True)

In [ ]:
df.shape

(891, 12)

### Handle Categorical Data

In [ ]:
pd.get_dummies(df)

PassengerId  Survived  Pclass   Age  SibSp  Parch     Fare  \
0              1         0       3  22.0      1      0   7.2500   
1              2         1       1  38.0      1      0  71.2833   
2              3         1       3  26.0      0      0   7.9250   
3              4         1       1  35.0      1      0  53.1000   
4              5         0       3  35.0      0      0   8.0500   
..           ...       ...     ...   ...    ...    ...      ...   
886          887         0       2  27.0      0      0  13.0000   
887          888         1       1  19.0      0      0  30.0000   
888          889         0       3  28.0      1      2  23.4500   
889          890         1       1  26.0      0      0  30.0000   
890          891         0       3  32.0      0      0   7.7500   

     Name_Abbing, Mr. Anthony  Name_Abbott, Mr. Rossmore Edward  \
0                           0                                 0   
1                           0                                 0   
2                           0                                 0   
3                           0                                 0   
4                           0                                 0   
..                        ...                               ...   
886                         0                                 0   
887                         0                                 0   
888                         0                                 0   
889                         0                                 0   
890                         0                                 0   

     Name_Abbott, Mrs. Stanton (Rosa Hunt)  ...  Cabin_F G73  Cabin_F2  \
0                                        0  ...            0         0   
1                                        0  ...            0         0   
2                                        0  ...            0         0   
3                                        0  ...            0         0   
4                                        0  ...            0         0   
..                                     ...  ...          ...       ...   
886                                      0  ...            0         0   
887                                      0  ...            0         0   
888                                      0  ...            0         0   
889                                      0  ...            0         0   
890                                      0  ...            0         0   

     Cabin_F33  Cabin_F38  Cabin_F4  Cabin_G6  Cabin_T  Embarked_C  \
0            0          0         0         0        0           0   
1            0          0         0         0        0           1   
2            0          0         0         0        0           0   
3            0          0         0         0        0           0   
4            0          0         0         0        0           0   
..         ...        ...       ...       ...      ...         ...   
886          0          0         0         0        0           0   
887          0          0         0         0        0           0   
888          0          0         0         0        0           0   
889          0          0         0         0        0           1   
890          0          0         0         0        0           0   

     Embarked_Q  Embarked_S  
0             0           1  
1             0           0  
2             0           1  
3             0           1  
4             0           1  
..          ...         ...  
886           0           1  
887           0           1  
888           0           1  
889           0           0  
890           1           0  

[891 rows x 1731 columns]

In [ ]:
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder, LabelEncoder

# One Hot Encoding
ohe = OneHotEncoder()
ohe.fit_transform(df[['Sex','Embarked']]).toarray()

array([[0., 1., 0., 0., 1.],
       [1., 0., 1., 0., 0.],
       [1., 0., 0., 0., 1.],
       ...,
       [1., 0., 0., 0., 1.],
       [0., 1., 1., 0., 0.],
       [0., 1., 0., 1., 0.]])

In [ ]:
# Ordianl Encoding
oe = OrdinalEncoder()
oe.fit_transform(df[['Sex','Embarked']])

array([[1., 2.],
       [0., 0.],
       [0., 2.],
       ...,
       [0., 2.],
       [1., 0.],
       [1., 1.]])

In [ ]:
# Lable Encoding
le = LabelEncoder()
le.fit_transform(df['Sex'])

array([1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1,
       0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0,
       1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0,

In [ ]:
# Cound Frequency Encoding
cabin_freq = df['Cabin'].value_counts().to_dict()

df['Cabin'].map(cabin_freq)/len(df)

0           NaN
1      0.001122
2           NaN
3      0.002245
4           NaN
         ...   
886         NaN
887    0.001122
888         NaN
889    0.001122
890         NaN
Name: Cabin, Length: 891, dtype: float64

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female  28.0      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

## Data Preprocessing

### Data Normalization

In [ ]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler

mms = MinMaxScaler()
mms.fit_transform(df[['Age','Fare']])

array([[0.27117366, 0.01415106],
       [0.4722292 , 0.13913574],
       [0.32143755, 0.01546857],
       ...,
       [0.34656949, 0.04577135],
       [0.32143755, 0.0585561 ],
       [0.39683338, 0.01512699]])

In [ ]:
ss = StandardScaler()
ss.fit_transform(df[['Age','Fare']])

array([[-0.56573646, -0.50244517],
       [ 0.66386103,  0.78684529],
       [-0.25833709, -0.48885426],
       ...,
       [-0.1046374 , -0.17626324],
       [-0.25833709, -0.04438104],
       [ 0.20276197, -0.49237783]])

### Data Transformation

In [ ]:
# Square Root Transformation
np.sqrt(df[['Age', 'Fare']])

Age      Fare
0    4.690416  2.692582
1    6.164414  8.442944
2    5.099020  2.815138
3    5.916080  7.286975
4    5.916080  2.837252
..        ...       ...
886  5.196152  3.605551
887  4.358899  5.477226
888  5.291503  4.842520
889  5.099020  5.477226
890  5.656854  2.783882

[891 rows x 2 columns]

In [ ]:
# log transformation
np.log(df[['Age','Fare']])

Age      Fare
0    3.091042  1.981001
1    3.637586  4.266662
2    3.258097  2.070022
3    3.555348  3.972177
4    3.555348  2.085672
..        ...       ...
886  3.295837  2.564949
887  2.944439  3.401197
888  3.332205  3.154870
889  3.258097  3.401197
890  3.465736  2.047693

[891 rows x 2 columns]

In [ ]:
# exponential transformation
np.exp(df[['Age','Fare']])

Age          Fare
0    3.584913e+09  1.408105e+03
1    3.185593e+16  9.077031e+30
2    1.957296e+11  2.765564e+03
3    1.586013e+15  1.150898e+23
4    1.586013e+15  3.133795e+03
..            ...           ...
886  5.320482e+11  4.424134e+05
887  1.784823e+08  1.068647e+13
888  1.446257e+12  1.528289e+10
889  1.957296e+11  1.068647e+13
890  7.896296e+13  2.321572e+03

[891 rows x 2 columns]